### Site Settings ###
locale              : "en"
title               : Rama Prashanth
description         : >-
                      I turn espresso :coffee: into code,
                      that grants free will :heart: to robots :robot:
url                 : ""
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ramaprashanth/ramaprashanth.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : ramaprashanth/ramaprashanth.github.io
github_username     : ramaprashanth
breadcrumbs         : false
words_per_minute    : 200


### Plugins ###
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate-v2


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - tags.html
  - 404.html
  - index.html
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Rama Prashanth
  image             : https://res.cloudinary.com/ramaprashanth/image/upload/v1583398653/dp_2019.jpg
# behance           : your_username
# dribbble          : your_username
  email             : rv@ramaprashanth.com
  facebook          : ramaprashanthrv
  github            : ramaprashanth
# gitlab            : your_username
  instagram         : ramaprashanthrv
  linkedin          : ramaprashanth
  medium            : ramaprashanth
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : ramaprashanthrv
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

google-analytics:
  id: "UA-158879927-1"


### Paginate
# Pagination settings
pagination:
  enabled: true
  debug: true
  per_page: 6
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
